version: "3"

services:
  #  postgres_register:
  #    container_name: ifood_postgres_register
  #    image: postgres:12.3-alpine
  #    environment:
  #      POSTGRES_USER: register
  #      POSTGRES_PASSWORD: register
  #    ports:
  #      - 5433:5432

  ifood_keycloak:
    container_name: ifood_keycloak
    image: jboss/keycloak:9.0.2
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - 8180:8080

  ifood_jaeger:
    container_name: ifood_jaeger
    image: jaegertracing/all-in-one:1.17
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411

  ifood_prometheus:
    container_name: ifood_prometheus
    image: ifood-prometheus
    network_mode: host

  ifood_grafana:
    container_name: ifood_grafana
    image: grafana/grafana:6.7.0
    network_mode: host

  ifood_artemis:
    container_name: ifood_artemis
    image: vromero/activemq-artemis:2.11.0
    environment:
      ARTEMIS_USERNAME: admin
      ARTEMIS_PASSWORD: admin
    network_mode: host

  ifood_mongodb:
    container_name: ifood_mongodb
    image: library/mongo:4-bionic
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: orders
    ports:
      - 27017:27017

  ifood_zookeeper:
    container_name: ifood_zookeeper
    image: debezium/zookeeper:1.3
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888

  ifood_kafka:
    container_name: ifood_kafka
    image: debezium/kafka:1.3
    environment:
      - ZOOKEEPER_CONNECT=ifood_zookeeper:2181
    ports:
      - 9092:9092
    links:
      - ifood_zookeeper

  ifood_kafdrop:
    container_name: ifood_kafdrop
    image: obsidiandynamics/kafdrop:3.27.0
    environment:
      KAFKA_BROKERCONNECT: ifood_kafka:9092
    ports:
      - 9001:9000
    depends_on:
      - ifood_kafka
