version: "3"

services:
  #  postgres_register:
  #    container_name: ifood_postgres_register
  #    image: postgres:12.3-alpine
  #    environment:
  #      POSTGRES_USER: register
  #      POSTGRES_PASSWORD: register
  #    ports:
  #      - 5433:5432

  keycloak_ifood:
    container_name: ifood_keycloak
    image: jboss/keycloak:9.0.2
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - 8180:8080
