version: "3"

#services:
#  postgres_register:
#    container_name: postgres_register_ifood
#    image: postgres:12.3-alpine
#    environment:
#      POSTGRES_USER: register
#      POSTGRES_PASSWORD: register
#    ports:
#      - 5433:5432
